export const ROLE_CAPABILITIES = {
  guest: {
    canViewMap: true,
    canViewPlacecard: true,
    canAddVenue: false,
    canRate: false,
    canComment: false,
    canRoute: false,
    canNavigate: false,
    canUploadPhotos: false,
    canSaveRoutes: false,
    canShareRoutes: false,
    canCreateGroups: false,
    canJoinGroups: false,
    canShareLocation: false,
  },

  user: {
    canViewMap: true,
    canViewPlacecard: true,
    canAddVenue: true,
    canRate: true,
    canComment: true,
    canRoute: true,
    canNavigate: true,
    canUploadPhotos: false,
    canSaveRoutes: false,
    canShareRoutes: false,
    canCreateGroups: false,
    canJoinGroups: false,
    canShareLocation: false,
  },

  pro: {
    canViewMap: true,
    canViewPlacecard: true,
    canAddVenue: true,
    canRate: true,
    canComment: true,
    canRoute: true,
    canNavigate: true,
    canUploadPhotos: true,
    canSaveRoutes: true,
    canShareRoutes: true,
    canCreateGroups: true,
    canJoinGroups: true,
    canShareLocation: true,
  },

  admin: {
    canViewMap: true,
    canViewPlacecard: true,
    canAddVenue: true,
    canRate: true,
    canComment: true,
    canRoute: true,
    canNavigate: true,
    canUploadPhotos: true,
    canSaveRoutes: true,
    canShareRoutes: true,
    canCreateGroups: true,
    canJoinGroups: true,
    canShareLocation: true,
    canEditAnyVenue: true,
    canDeleteAnyVenue: true,
    canModerateUsers: true,
  }
};
